version: '3'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: testing_system
      POSTGRES_USER: server
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
