# Generated by Django 5.0.1 on 2024-06-29 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('study_group_name', models.CharField(max_length=100)),
                ('study_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_group_img_link', models.URLField()),
                ('members', models.ManyToManyField(related_name='study_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
