# Generated by Django 5.0.1 on 2024-07-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0004_userteststatus_grade_userteststatus_score_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
