# Generated by Django 5.0.1 on 2024-01-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.answervariant')),
            ],
        ),
        migrations.CreateModel(
            name='TestSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.test')),
            ],
        ),
    ]
